blank_issues_enabled: false
contact_links:
  - name: Features, Bug Reports, Questions
    url: https://github.com/open-source-hunt/hunt/discussions
    about: Our preferred starting point if you have any questions or suggestions about configuration, features or behavior.
